llm:
  provider: openai
  model: qwen2.5:7b
  base_url: http://127.0.0.1:11434/v1/chat/completions
  api_key: ${BIDDING_ASSISTANT_LLM_API_KEY:-dummy}
  timeout: 150
retrieval:
  enable_heuristic: true
  enable_embedding: false
  limit: 6
